// list
export const LIST_REQUEST = 'LIST_REQUEST';
export const LIST_SEARCH_REQUEST = 'LIST_SEARCH_REQUEST';
export const LIST_SUCCESS = 'LIST_SUCCESS';
export const LIST_FAILED = 'LIST_FAILED';
export const LIST_CLEAR_STATE = 'LIST_CLEAR_STATE';

// details
export const DETAIL_STORE_REQUEST = 'DETAIL_STORE_REQUEST';
export const DETAIL_STORE_SUCCESS = 'DETAIL_STORE_SUCCESS';
export const DETAIL_STORE_FAILED = 'DETAIL_STORE_FAILED';
export const DETAIL_STORE_CLEAR_STATE = 'DETAIL_STORE_CLEAR_STATE';

// details product
export const DETAIL_STORE_PRODUCT_REQUEST = 'DETAIL_STORE_PRODUCT_REQUEST';
export const DETAIL_STORE_PRODUCT_SUCCESS = 'DETAIL_STORE_PRODUCT_SUCCESS';
export const DETAIL_STORE_PRODUCT_FAILED = 'DETAIL_STORE_PRODUCT_FAILED';
export const DETAIL_STORE_PRODUCT_CLEAR_STATE = 'DETAIL_STORE_PRODUCT_CLEAR_STATE';

// cart
export const CART_SET = 'CART_SET'
export const CART_DELETE = 'CART_DELETE'
export const CART_CLEAR = 'CART_CLEAR'